import { afterEach, describe, expect, it, vi } from 'vitest';
import { createWebWorkspaceClient } from '../src/client.js';

const SOURCE = 'Dungeonlab+pulse:0,1,8=27,7,32,3,1/0-1,50-0,100-1';

afterEach(() => {
  vi.unstubAllGlobals();
});

describe('web workspace client', () => {
  it('keeps the render descriptor and generated bytes together', async () => {
    const descriptor = {
      displayName: 'pulse-preview.svg',
      format: 'svg',
      byteSize: 6,
      width: 1200,
      height: 520,
      streamDigest: '0123456789abcdef',
      contentType: 'image/svg+xml'
    };
    const fetchMock = vi.fn().mockResolvedValue(new Response('<svg/>', {
      status: 200,
      headers: {
        'content-type': 'image/svg+xml',
        'content-disposition': 'attachment; filename="pulse-preview.svg"',
        'x-pulse-result': JSON.stringify(descriptor)
      }
    }));
    vi.stubGlobal('fetch', fetchMock);

    const operation = await createWebWorkspaceClient().renderPreview({
      displayName: 'source.pulse',
      digest: 'fedcba9876543210',
      text: SOURCE
    }, 'svg');

    expect(operation.envelope.status).toBe('success');
    expect(operation.envelope.result).toEqual(descriptor);
    expect(operation.artifact?.displayName).toBe('pulse-preview.svg');
    expect(operation.artifact?.bytes.byteLength).toBe(6);
    expect(fetchMock).toHaveBeenCalledWith('/api/v1/pulses/preview', expect.objectContaining({
      method: 'POST'
    }));
  });

  it('uses a JPEG fallback name for QR image exports', async () => {
    const descriptor = {
      format: 'qr-envelope',
      displayName: 'pulse.qr.jpg',
      byteSize: 3,
      mode: 'canonical',
      sourceDigest: '0123456789abcdef',
      roundTripVerified: true,
      contentType: 'image/jpeg'
    };
    const fetchMock = vi.fn().mockResolvedValue(new Response(new Uint8Array([0xff, 0xd8, 0xff]), {
      status: 200,
      headers: {
        'content-type': 'image/jpeg',
        'x-pulse-result': JSON.stringify(descriptor)
      }
    }));
    vi.stubGlobal('fetch', fetchMock);

    const operation = await createWebWorkspaceClient().export({
      displayName: 'source.pulse',
      digest: 'fedcba9876543210',
      text: SOURCE
    }, 'qr-envelope', 'canonical');

    expect(operation.envelope.status).toBe('success');
    expect(operation.artifact?.displayName).toBe('pulse.qr.jpg');
    expect(operation.artifact?.contentType).toContain('image/jpeg');
    expect(Array.from(operation.artifact?.bytes ?? [])).toEqual([0xff, 0xd8, 0xff]);
  });

  it('omits an unspecified batch export mode so the API applies its default', async () => {
    const responseEnvelope = {
      schemaVersion: 'pulse-contract-v1',
      ruleVersion: 'pulse-rules-v1',
      operation: 'batch',
      status: 'rejected',
      result: null,
      diagnostics: [{
        code: 'PULSE_TASK_INPUT_LIMIT',
        severity: 'error',
        stage: 'resource',
        message: 'Batch input was rejected.',
        location: { path: '$' }
      }]
    } as const;
    const fetchMock = vi.fn().mockResolvedValue(new Response(JSON.stringify(responseEnvelope), {
      status: 422,
      headers: { 'content-type': 'application/json' }
    }));
    vi.stubGlobal('fetch', fetchMock);

    const operation = await createWebWorkspaceClient().batchExport([
      { name: 'source.pulse', bytes: new TextEncoder().encode(SOURCE) }
    ]);

    expect(operation.envelope.status).toBe('rejected');
    const request = fetchMock.mock.calls[0]?.[1] as RequestInit | undefined;
    expect(JSON.parse(String(request?.body))).toEqual({
      items: [{ id: 'web-1', displayName: 'source.pulse', text: SOURCE }]
    });
  });
});
